module AndroidKeyEvents
  def send_events_for(message_arr, dut = @equipment['dut1'])

      worker_arr = message_arr.dup
      worker_arr = [worker_arr] if !worker_arr.kind_of?(Array)

      event_vals = {
	      '0' => 7,
	      '1' => 8,
	      '2' => 9,
	      '3' => 10,
	      '4' => 11,
	      '5' => 12,
	      '6' => 13,
	      '7' => 14,
	      '8' => 15,
	      '9' => 16,
	      'a' => 29,
	      '__left_alt_modifier__' => 57,
	      '__right_alt_modifier__' => 58,
	      "'" => 75,
	      '@' => 77,
	      'b' => 30,
	      '__back__' => 4,
	      '\\' => 73,
	      '__a_button__' => 96,
	      '__b_button__' => 97,
	      '__c_button__' => 98,
	      '__l1_button__' => 102,
	      '__l2_button__' => 104,
	      '__mode_button__' => 110,
	      '__r1_button__' => 103,
	      '__r2_button__' => 105,
	      '__select_button__' => 109,
	      '__start_button__' => 108,
	      '__left_thumb_button__' => 106,
	      '__right_thumb_button__' => 107,
	      '__x_button__' => 99,
	      '__y_button__' => 100,
	      '__z_button__' => 101,
	      'c' => 31,
	      '__call__' => 5,
	      '__camera__' => 27,
	      '__clear__' => 28,
	      ',' => 55,
	      'd' => 32,
	      '__backspace__' => 67,
	      '__directional_pad_center__' => 23,
	      '__directional_pad_down__' => 20,
	      '__directional_pad_left__' => 21,
	      '__directional_pad_right__' => 22,
	      '__directional_pad_up__' => 19,
	      'e' => 33,
	      '__end_call__' => 6,
	      '__enter__' => 66,
	      '__envelope_special_function__' => 65,
	      '=' => 70,
	      '__explorer_special_function__' => 64,
	      'f' => 34,
	      '__camera_focus__' => 80,
	      'g' => 35,
	      '`' => 68,
	      'h' => 36,
	      '__headset_hook__' => 79,
	      '__home__' => 3,
	      'i' => 37,
	      'j' => 38,
	      'k' => 39,
	      'l' => 40,
	      '[' => 71,
	      'm' => 41,
	      '__fast_forward_media__' => 90,
	      '__play_next_media__' => 87,
	      '__play/pause_media__' => 85,
	      '__play_previous_media__' => 88,
	      '__rewind_media__' => 89,
	      '__stop_media__' => 86,
	      '__menu__' => 82,
	      '__mute__' => 91,
	      'n' => 42,
	      '__notification__' => 83,
	      '__number_modifier__' => 78,
	      'o' => 43,
	      'p' => 44,
	      '__page_down__' => 93,
	      '__page_up__' => 92,
	      '.' => 56,
	      '__picture_symbols_modifier__' => 94,
	      '+' => 81,
	      '#' => 18,
	      '__power__' => 26,
	      'q' => 45,
	      'r' => 46,
	      ']' => 72,
	      's' => 47,
	      '__search__' => 84,
	      ';' => 74,
	      '__left_shift_modifier__' => 59,
	      '__right_shift_modifier__' => 60,
	      '/' => 76,
	      '__soft_left__' => 1,
	      '__soft_right__' => 2,
	      '__space__' => 62,
	      '*' => 17,
	      '__switch_charset_modifier__' => 95,
	      '__symbol_modifier__' => 63,
	      't' => 48,
	      '__tab__' => 61,
	      'u' => 49,
	      '__unknown__' => 0,
	      'v' => 50,
	      '__volume_down__' => 25,
	      '__volume_up__' => 24,
	      'w' => 51,
	      'x' => 52,
	      'y' => 53,
	      'z' => 54,
      }

      worker_arr.each do |current_string|
        if(event_vals.has_key?(current_string))
          dut.send_adb_cmd("shell input keyevent #{event_vals[current_string]}")
        else
          current_string.each_char do |current_char|
            dut.send_adb_cmd("shell input keyevent #{event_vals[current_char]}")
          end
        end
      end
  end
end

