export  PRODUCT                       = LSP 2.0
export  PLATFORM                      = DM646x
export  VERSION		        = 02.01.01.00

#   =========================================================
#   Setting Compilation Options.
#   =========================================================
export  DEBUG_BUILD                   = 0
export  USE_PT                        = 1
export  USE_TP                        = 1
export  USE_TP_USER                   = 1
export  USE_TP_I2C                    = 1
export  USE_TP_SPI                    = 1
export  USE_TP_V4L2                   = 1
export  USE_TP_VDCE                   = 1
export  USE_TP_USBVIDEO               = 1
export  USE_TP_FBDEV                  = 0
export  USE_TP_FS                     = 1
export  USE_TP_OSS                    = 1
export  USE_TP_ALSA                   = 1
export  USE_TP_KERNEL                 = 1
export  USE_TP_VLYNQ                  = 1
export  USE_TP_EDMA                   = 1


