# -*- coding: ISO-8859-1 -*-
require 'FileUtils'
INPUT_DIR = "\\\\gtsnowball\\System_Test\\Automation\\gtsystst\\video_files\\VGDK_logs\\input"
VGDK_SCRIPTS = File.join(File.expand_path(File.dirname(__FILE__)))

iter_id = ARGV[0]
puts "iter_id : #{iter_id}"
num_pcap_files_total = 0
pcap_files = []
Dir.foreach("#{INPUT_DIR}\\config\\autogenerated") { |file|
    if /#{iter_id}/.match(file)
      puts "Found file #{INPUT_DIR}\\config\\autogenerated\\#{File.basename(file)}.cfg"
      cfg_file = File.open("#{INPUT_DIR}\\config\\autogenerated\\#{File.basename(file)}", "r")
      if(/3/.match(cfg_file.gets.chomp.to_s)) #merge PCAP file option
        #puts "Reading first PCAP merge file"
        num_pcap_files = cfg_file.gets.chomp.to_i
        puts "num_pcap_files :#{num_pcap_files}"
        num_pcap_files.times do
          pcap_files << cfg_file.gets.chomp.to_s
        end
      num_pcap_files_total += num_pcap_files
      end
      cfg_file.close
      puts num_pcap_files_total
    end
    }
auto_gen_cfg_file = File.new("#{INPUT_DIR}\\config\\autogenerated\\auto_generated_ConfigFile_Iter#{iter_id}.cfg", "w")
auto_gen_cfg_file.puts "3" # Merge PCAP files
auto_gen_cfg_file.puts num_pcap_files_total
pcap_files.each { |file|
  auto_gen_cfg_file.puts file
}
auto_gen_cfg_file.puts "#{INPUT_DIR}\\out\\Iter#{iter_id}_to_tomahawk.cap"
auto_gen_cfg_file.close
system("#{VGDK_SCRIPTS}/etherealUtil.exe #{INPUT_DIR}\\config\\autogenerated\\auto_generated_ConfigFile_Iter#{iter_id}.cfg #{INPUT_DIR}\\config\\autogenerated\\auto_generated_ConfigFile_4sendPkts_Iter#{iter_id}.cfg")